name: push-build-release
run-name: ${{ github.actor }} ${{github.event_name}} to: ${{ github.base_ref }} 
on: 
  push:
    tags:
      - 'v*'
  pull_request:
    types: [opened,reopened]
    branches: [develop]
  pull_request_target:
    types: [closed]
    branches: [main]  
jobs:
  build_test_package:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        sharedLib: [on,off]
        useThread: [on,off]
        build_docs: 
          - ${{ github.event.pull_request.merged == true && startsWith(github.base_ref, 'main') }}
        exclude:
          - build_docs: true
            os: [macos-latest,windows-latest]
          - build_docs: true
            sharedLib: [on]  
          - build_docs: true
            useThread: [on]  


    runs-on: ${{ matrix.os }}
    continue-on-error: true  

    steps:
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies on windows
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake doxygen
          ninja --version
          cmake --version
          gcc --version
          
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install cmake ninja
          ninja --version
          cmake --version

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'

      - name: Create build directory
        run:  cmake -E make_directory ${{runner.temp}}/build

      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: qt-cmake -G Ninja -DCMAKE_BUILD_TYPE="release" -DUSE_THREADS=${{ matrix.useThread }} -DBUILD_TESTING=ON -DBUILD_DOCS=${{ matrix.build_docs }} -DCMAKE_INSTALL_PREFIX="../install" -DBUILD_SHARED_LIBS=${{ matrix.sharedLib }} ${{ github.workspace }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build .   

      - name: Test
        working-directory: ${{ runner.temp }}/build
        run: ninja test

      - name: Install
        working-directory: ${{ runner.temp }}/build
        run: cmake --install .

      - name: Binary Package
        working-directory: ${{ runner.temp }}/build
        run: |
          cpack -B package --config CPackConfig.cmake
          cmake -E remove_directory package/_CPack_Packages
      

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_sharedlib_${{ matrix.sharedLib }}
          path: ${{ runner.temp }}/build/package/* 
      
      - uses: actions/upload-pages-artifact@v1.0.8
        if: startsWith(matrix.build_docs,'on')
        with:
          path: ${{ github.workspace }}/doc/html/ 

  release:
    needs: build_test_package
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
          
      - uses: actions/checkout@v3
    
      - uses: actions/download-artifact@v3
        with:
           path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Releases 
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*/*

  deploy_page:
    needs: build_test_package
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      pages: write      
      id-token: write  

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
